### ISSUE TITLE
Issues in preprocessing for GLN

### ISSUE THREAD

**Issue by ZhichaoTan** [coleygroup/rxn-ebm#10]
Hello, the rxn-ebm project is indeed inspiring. However, when I attempted to preprocess the USPTO-50K data for GLN and run bash scripts/gln_preprocess.sh, the following issue was encountered:

```
Checking data format before preprocessing
Checking the first 100 entries for each file
Data format check passed
Step 4: building all reactions
loading data info from ./data/gln_schneider50k/processed/cooked_schneider50k/tpl-default
loading templates
11753it [00:00, 263949.06it/s]
# unique templates 11753
# raw train loaded: 39713
loading positive tpls
Traceback (most recent call last):
  File "/home/yuxuan/Zhichao_repo/rxn-ebm/rxnebm/proposer/gln_openretro/preprocess.py", line 97, in <module>
    preprocess_main(args)
  File "/home/yuxuan/Zhichao_repo/rxn-ebm/rxnebm/proposer/gln_openretro/preprocess.py", line 71, in preprocess_main
    processor.preprocess()
  File "/home/yuxuan/Zhichao_repo/rxn-ebm/rxnebm/proposer/gln_openretro/models/gln_model/gln_processor.py", line 129, in preprocess
    self.build_all_reactions()                  # step 4
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuxuan/Zhichao_repo/rxn-ebm/rxnebm/proposer/gln_openretro/models/gln_model/gln_processor.py", line 432, in build_all_reactions
    DataInfo.load_cooked_part("train", part=pid, load_graphs=False)
  File "/home/yuxuan/Zhichao_repo/rxn-ebm/rxnebm/proposer/gln_openretro/models/gln_model/gln/data_process/data_info.py", line 82, in load_cooked_part
    header = next(reader)
             ^^^^^^^^^^^^
StopIteration
```

**Comment by connorcoley** [comment]
It looks like this might originate from the openretro repo instead of the rxn-ebm repo; do you mind re-opening an issue there?

**Comment by ZhichaoTan** [comment]
This issue has been solved by using the preprocessing code in the original GLN repository. Thank you for the kind reply!
